# Generated by Django 5.2.8 on 2025-11-18 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, help_text='User who made the request (null for anonymous)', null=True)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('path', models.CharField(db_index=True, help_text='Request URL path', max_length=512)),
                ('status_code', models.IntegerField(db_index=True, help_text='HTTP response status code')),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address (IPv4 or IPv6)')),
                ('user_agent', models.TextField(blank=True, default='', help_text='User-Agent header (truncated)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Log entry timestamp')),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'db_table': 'api_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'user_id'], name='api_log_user_time_idx'), models.Index(fields=['path', '-created_at'], name='api_log_path_time_idx'), models.Index(fields=['status_code'], name='api_log_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, help_text='User associated with error (if applicable)', null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Error severity level', max_length=20)),
                ('error_type', models.CharField(db_index=True, help_text='Exception type or error category', max_length=255)),
                ('message', models.TextField(help_text='Error message or summary')),
                ('stack_trace', models.TextField(blank=True, default='', help_text='Full exception traceback')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context (request data, user state, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Error occurrence timestamp')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'db_table': 'error_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'severity'], name='error_log_sev_time_idx'), models.Index(fields=['error_type'], name='error_log_type_idx')],
            },
        ),
    ]
