# Generated by Django 5.1.14 on 2025-11-06 23:41

import django.core.validators
import django.db.models.functions.datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("warning", "Предупреждение"),
                            ("error", "Ошибка"),
                            ("critical", "Критическая"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыт"),
                            ("in_progress", "В процессе"),
                            ("closed", "Закрыт"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "ai_confidence",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "diagnostics_diagnosticreport",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HydraulicSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("industrial", "Промышленная"),
                            ("mobile", "Мобильная"),
                            ("marine", "Морская"),
                            ("aviation", "Авиационная"),
                            ("construction", "Строительная"),
                            ("mining", "Горнодобывающая"),
                            ("agricultural", "Сельскохозяйственная"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("maintenance", "На обслуживании"),
                            ("inactive", "Неактивна"),
                            ("emergency", "Аварийная"),
                            ("decommissioned", "Списана"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("components_count", models.PositiveIntegerField(default=0)),
                (
                    "last_reading_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "diagnostics_hydraulicsystem",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegratedDiagnosticResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "math_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "phase_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "tribo_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "integrated_score",
                    models.FloatField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("normal", "Норма"),
                            ("warning", "Предупреждение"),
                            ("fault", "Неисправность"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "predicted_remaining_life",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "confidence_level",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("recommendations", models.TextField()),
                ("priority_actions", models.JSONField(blank=True, default=list)),
                ("diagnosis_duration", models.FloatField(default=0.0)),
                (
                    "data_quality_score",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "diagnostics_integratedresult",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MathematicalModelResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "measured_pressure",
                    models.FloatField(help_text="Измеренное давление, МПа"),
                ),
                (
                    "measured_flow",
                    models.FloatField(help_text="Измеренный расход, л/мин"),
                ),
                (
                    "measured_speed",
                    models.FloatField(help_text="Измеренная скорость, об/мин"),
                ),
                (
                    "calculated_pressure",
                    models.FloatField(help_text="Расчетное давление, МПа"),
                ),
                (
                    "calculated_flow",
                    models.FloatField(help_text="Расчетный расход, л/мин"),
                ),
                (
                    "calculated_speed",
                    models.FloatField(help_text="Расчетная скорость, об/мин"),
                ),
                (
                    "pressure_deviation",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "flow_deviation",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "speed_deviation",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "max_deviation",
                    models.FloatField(
                        db_index=True,
                        help_text="Максимальное отклонение, %",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Норма"),
                            ("warning", "Предупреждение"),
                            ("fault", "Неисправность"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        db_index=True,
                        help_text="Оценка 0.0-1.0",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("recommendations", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "diagnostics_mathmodelresult",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PhasePortraitResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "recording_duration",
                    models.FloatField(default=20.0, help_text="Длительность, сек"),
                ),
                (
                    "sampling_frequency",
                    models.FloatField(default=100.0, help_text="Частота, Гц"),
                ),
                (
                    "portrait_type",
                    models.CharField(
                        choices=[
                            ("velocity_position", "V=f(x)"),
                            ("force_velocity", "F=f(V)"),
                            ("pressure_flow", "P=f(Q)"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("calculated_area", models.FloatField()),
                ("reference_area", models.FloatField()),
                (
                    "area_deviation",
                    models.FloatField(
                        db_index=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("center_shift_x", models.FloatField(default=0.0)),
                ("center_shift_y", models.FloatField(default=0.0)),
                ("contour_breaks", models.IntegerField(default=0)),
                ("shape_distortion", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Норма"),
                            ("pre_fault", "Предотказ"),
                            ("fault", "Отказ"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("recommendations", models.TextField(blank=True, default="")),
                (
                    "portrait_image_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "diagnostics_phaseportraitresult",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("pressure", "Давление"),
                            ("temperature", "Температура"),
                            ("flow", "Поток"),
                            ("vibration", "Вибрация"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(float("-inf"))
                        ]
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                ("is_critical", models.BooleanField(db_index=True, default=False)),
                (
                    "warning_message",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                (
                    "day_bucket",
                    models.GeneratedField(
                        db_index=True,
                        db_persist=True,
                        expression=django.db.models.functions.datetime.TruncDay(
                            "timestamp"
                        ),
                        output_field=models.DateField(),
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "diagnostics_sensordata",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "specification",
                    models.TextField(
                        blank=True,
                        help_text="Free-form component specification",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "diagnostics_systemcomponent",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TribodiagnosticResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("sample_volume", models.FloatField(default=100.0)),
                (
                    "sample_location",
                    models.CharField(default="Основной бак", max_length=100),
                ),
                ("particles_4um", models.IntegerField(default=0)),
                ("particles_6um", models.IntegerField(default=0)),
                ("particles_14um", models.IntegerField(default=0)),
                (
                    "iso_class",
                    models.CharField(
                        db_index=True, help_text="Напр. 15/13/10", max_length=20
                    ),
                ),
                ("iron_ppm", models.FloatField(default=0.0)),
                ("copper_ppm", models.FloatField(default=0.0)),
                ("aluminum_ppm", models.FloatField(default=0.0)),
                ("chromium_ppm", models.FloatField(default=0.0)),
                ("silicon_ppm", models.FloatField(default=0.0)),
                ("viscosity_cst", models.FloatField(default=0.0)),
                (
                    "ph_level",
                    models.FloatField(
                        default=7.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(14.0),
                        ],
                    ),
                ),
                ("water_content_ppm", models.FloatField(default=0.0)),
                (
                    "wear_source",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Норма"),
                            ("attention", "Внимание"),
                            ("critical", "Критическое"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "lab_report_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "analyzed_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("recommendations", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("analysis_date", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "diagnostics_tribodiagnosticresult",
                "ordering": ["-analysis_date"],
            },
        ),
    ]
