# Generated by Django on 2025-10-15 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название оборудования')),
                ('equipment_type', models.CharField(choices=[('pump', 'Насос'), ('valve', 'Клапан'), ('cylinder', 'Цилиндр'), ('motor', 'Мотор'), ('filter', 'Фильтр')], max_length=50, verbose_name='Тип оборудования')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('operational', 'Работает'), ('maintenance', 'На обслуживании'), ('faulty', 'Неисправно'), ('retired', 'Списано')], default='operational', max_length=50, verbose_name='Статус')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Последнее обслуживание')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Следующее обслуживание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='diagnostics.hydraulicsystem', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название диагностики')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Не удалось')], default='pending', max_length=50, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Результаты')),
                ('root_cause', models.TextField(blank=True, null=True, verbose_name='Причина')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='Решение')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='Достоверность ИИ (%)')),
                ('ai_suggestions', models.TextField(blank=True, null=True, verbose_name='Предложения ИИ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='diagnostics.equipment', verbose_name='Оборудование')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='diagnostics.hydraulicsystem', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Диагностика',
                'verbose_name_plural': 'Диагностики',
                'db_table': 'diagnoses',
                'ordering': ['-created_at'],
            },
        ),
    ]
