# Generated by Django 5.2.8 on 2025-11-18 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GNNModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(db_index=True, max_length=30)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(help_text='Filesystem or artifact path to model file', max_length=255)),
                ('size_mb', models.FloatField(default=0, help_text='Model size in MB')),
                ('framework', models.CharField(help_text='onnx, pytorch, etc.', max_length=32)),
                ('input_shape', models.CharField(help_text='Comma-separated shape (e.g., 1,10,32)', max_length=64)),
                ('output_classes', models.PositiveSmallIntegerField(default=3)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False, help_text='Is this model currently in production?')),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GNN Model Configuration',
                'verbose_name_plural': 'GNN Model Configurations',
                'db_table': 'gnn_model_config',
                'ordering': ['-deployed_at'],
                'indexes': [models.Index(fields=['model_version', 'is_active'], name='model_version_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='GNNTrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('stopped', 'Stopped')], db_index=True, default='queued', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('dataset_path', models.CharField(max_length=255)),
                ('experiment_name', models.CharField(max_length=128)),
                ('tensorboard_url', models.CharField(blank=True, default='', max_length=255)),
                ('last_metrics', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GNN Training Job',
                'verbose_name_plural': 'GNN Training Jobs',
                'db_table': 'gnn_training_job',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_id', 'status'], name='jobid_status_idx')],
            },
        ),
    ]
