
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'Placeholder': typeof import("../../components/Placeholder.vue")['default']
  'FigmaImageWithFallback': typeof import("../../components/figma/ImageWithFallback")['default']
  'LayoutAppHeader': typeof import("../../components/layout/app-header")['default']
  'LayoutAppSidebar': typeof import("../../components/layout/app-sidebar")['default']
  'PagesAuthPage': typeof import("../../components/pages/auth-page")['default']
  'PagesChatPage': typeof import("../../components/pages/chat-page")['default']
  'PagesDashboardPage': typeof import("../../components/pages/dashboard-page")['default']
  'PagesDiagnosticsPage': typeof import("../../components/pages/diagnostics-page")['default']
  'PagesEquipmentListPage': typeof import("../../components/pages/equipment-list-page")['default']
  'PagesReportsPage': typeof import("../../components/pages/reports-page")['default']
  'PagesSettingsPage': typeof import("../../components/pages/settings-page")['default']
  'UiAccordion': typeof import("../../components/ui/accordion")['default']
  'UiAlertDescription': typeof import("../../components/ui/alert-description.vue")['default']
  'UiAlertDialog': typeof import("../../components/ui/alert-dialog")['default']
  'UiAlertTitle': typeof import("../../components/ui/alert-title.vue")['default']
  'UiAlert': typeof import("../../components/ui/alert")['default']
  'UiAspectRatio': typeof import("../../components/ui/aspect-ratio")['default']
  'UiAvatarFallback': typeof import("../../components/ui/avatar-fallback.vue")['default']
  'UiAvatarImage': typeof import("../../components/ui/avatar-image.vue")['default']
  'UiAvatar': typeof import("../../components/ui/avatar")['default']
  'UiBadge': typeof import("../../components/ui/badge")['default']
  'UiBreadcrumb': typeof import("../../components/ui/breadcrumb")['default']
  'UiButton': typeof import("../../components/ui/button")['default']
  'UiCalendar': typeof import("../../components/ui/calendar")['default']
  'UiCardAction': typeof import("../../components/ui/card-action.vue")['default']
  'UiCardContent': typeof import("../../components/ui/card-content.vue")['default']
  'UiCardDescription': typeof import("../../components/ui/card-description.vue")['default']
  'UiCardFooter': typeof import("../../components/ui/card-footer.vue")['default']
  'UiCardHeader': typeof import("../../components/ui/card-header.vue")['default']
  'UiCardTitle': typeof import("../../components/ui/card-title.vue")['default']
  'UiCard': typeof import("../../components/ui/card")['default']
  'UiCarousel': typeof import("../../components/ui/carousel")['default']
  'UiChartArea': typeof import("../../components/ui/chart-area.vue")['default']
  'UiChartBar': typeof import("../../components/ui/chart-bar.vue")['default']
  'UiChartLine': typeof import("../../components/ui/chart-line.vue")['default']
  'UiChart': typeof import("../../components/ui/chart")['default']
  'UiCheckbox': typeof import("../../components/ui/checkbox")['default']
  'UiCollapsible': typeof import("../../components/ui/collapsible")['default']
  'UiCommand': typeof import("../../components/ui/command")['default']
  'UiContextMenu': typeof import("../../components/ui/context-menu")['default']
  'UiDialogDescription': typeof import("../../components/ui/dialog-description.vue")['default']
  'UiDialogFooter': typeof import("../../components/ui/dialog-footer.vue")['default']
  'UiDialogHeader': typeof import("../../components/ui/dialog-header.vue")['default']
  'UiDialogTitle': typeof import("../../components/ui/dialog-title.vue")['default']
  'UiDialog': typeof import("../../components/ui/dialog")['default']
  'UiDrawer': typeof import("../../components/ui/drawer")['default']
  'UiDropdownMenuItem': typeof import("../../components/ui/dropdown-menu-item.vue")['default']
  'UiDropdownMenuLabel': typeof import("../../components/ui/dropdown-menu-label.vue")['default']
  'UiDropdownMenuSeparator': typeof import("../../components/ui/dropdown-menu-separator.vue")['default']
  'UiDropdownMenu': typeof import("../../components/ui/dropdown-menu")['default']
  'UiFab': typeof import("../../components/ui/fab.vue")['default']
  'UiForm': typeof import("../../components/ui/form")['default']
  'UiHoverCard': typeof import("../../components/ui/hover-card")['default']
  'UiInputOtp': typeof import("../../components/ui/input-otp")['default']
  'UiInput': typeof import("../../components/ui/input")['default']
  'UiLabel': typeof import("../../components/ui/label")['default']
  'UiMenubar': typeof import("../../components/ui/menubar")['default']
  'UiNavigationMenu': typeof import("../../components/ui/navigation-menu")['default']
  'UiPagination': typeof import("../../components/ui/pagination")['default']
  'UiPopover': typeof import("../../components/ui/popover")['default']
  'UiProgress': typeof import("../../components/ui/progress")['default']
  'UiRadioGroupItem': typeof import("../../components/ui/radio-group-item.vue")['default']
  'UiRadioGroup': typeof import("../../components/ui/radio-group")['default']
  'UiResizable': typeof import("../../components/ui/resizable")['default']
  'UiScrollArea': typeof import("../../components/ui/scroll-area")['default']
  'UiSelectItem': typeof import("../../components/ui/select-item.vue")['default']
  'UiSelect': typeof import("../../components/ui/select")['default']
  'UiSeparator': typeof import("../../components/ui/separator")['default']
  'UiSheet': typeof import("../../components/ui/sheet")['default']
  'UiSidebar': typeof import("../../components/ui/sidebar")['default']
  'UiSkeleton': typeof import("../../components/ui/skeleton")['default']
  'UiSlider': typeof import("../../components/ui/slider")['default']
  'UiSonner': typeof import("../../components/ui/sonner")['default']
  'UiSwitch': typeof import("../../components/ui/switch")['default']
  'UiTable': typeof import("../../components/ui/table")['default']
  'UiTabsContent': typeof import("../../components/ui/tabs-content.vue")['default']
  'UiTabsList': typeof import("../../components/ui/tabs-list.vue")['default']
  'UiTabsTrigger': typeof import("../../components/ui/tabs-trigger.vue")['default']
  'UiTabs': typeof import("../../components/ui/tabs")['default']
  'UiTextarea': typeof import("../../components/ui/textarea")['default']
  'UiToast': typeof import("../../components/ui/toast.vue")['default']
  'UiToggleGroupItem': typeof import("../../components/ui/toggle-group-item.vue")['default']
  'UiToggleGroup': typeof import("../../components/ui/toggle-group")['default']
  'UiToggle': typeof import("../../components/ui/toggle")['default']
  'UiTooltip': typeof import("../../components/ui/tooltip")['default']
  'UiUseMobile': typeof import("../../components/ui/use-mobile")['default']
  'UiUtils': typeof import("../../components/ui/utils")['default']
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyPlaceholder': LazyComponent<typeof import("../../components/Placeholder.vue")['default']>
  'LazyFigmaImageWithFallback': LazyComponent<typeof import("../../components/figma/ImageWithFallback")['default']>
  'LazyLayoutAppHeader': LazyComponent<typeof import("../../components/layout/app-header")['default']>
  'LazyLayoutAppSidebar': LazyComponent<typeof import("../../components/layout/app-sidebar")['default']>
  'LazyPagesAuthPage': LazyComponent<typeof import("../../components/pages/auth-page")['default']>
  'LazyPagesChatPage': LazyComponent<typeof import("../../components/pages/chat-page")['default']>
  'LazyPagesDashboardPage': LazyComponent<typeof import("../../components/pages/dashboard-page")['default']>
  'LazyPagesDiagnosticsPage': LazyComponent<typeof import("../../components/pages/diagnostics-page")['default']>
  'LazyPagesEquipmentListPage': LazyComponent<typeof import("../../components/pages/equipment-list-page")['default']>
  'LazyPagesReportsPage': LazyComponent<typeof import("../../components/pages/reports-page")['default']>
  'LazyPagesSettingsPage': LazyComponent<typeof import("../../components/pages/settings-page")['default']>
  'LazyUiAccordion': LazyComponent<typeof import("../../components/ui/accordion")['default']>
  'LazyUiAlertDescription': LazyComponent<typeof import("../../components/ui/alert-description.vue")['default']>
  'LazyUiAlertDialog': LazyComponent<typeof import("../../components/ui/alert-dialog")['default']>
  'LazyUiAlertTitle': LazyComponent<typeof import("../../components/ui/alert-title.vue")['default']>
  'LazyUiAlert': LazyComponent<typeof import("../../components/ui/alert")['default']>
  'LazyUiAspectRatio': LazyComponent<typeof import("../../components/ui/aspect-ratio")['default']>
  'LazyUiAvatarFallback': LazyComponent<typeof import("../../components/ui/avatar-fallback.vue")['default']>
  'LazyUiAvatarImage': LazyComponent<typeof import("../../components/ui/avatar-image.vue")['default']>
  'LazyUiAvatar': LazyComponent<typeof import("../../components/ui/avatar")['default']>
  'LazyUiBadge': LazyComponent<typeof import("../../components/ui/badge")['default']>
  'LazyUiBreadcrumb': LazyComponent<typeof import("../../components/ui/breadcrumb")['default']>
  'LazyUiButton': LazyComponent<typeof import("../../components/ui/button")['default']>
  'LazyUiCalendar': LazyComponent<typeof import("../../components/ui/calendar")['default']>
  'LazyUiCardAction': LazyComponent<typeof import("../../components/ui/card-action.vue")['default']>
  'LazyUiCardContent': LazyComponent<typeof import("../../components/ui/card-content.vue")['default']>
  'LazyUiCardDescription': LazyComponent<typeof import("../../components/ui/card-description.vue")['default']>
  'LazyUiCardFooter': LazyComponent<typeof import("../../components/ui/card-footer.vue")['default']>
  'LazyUiCardHeader': LazyComponent<typeof import("../../components/ui/card-header.vue")['default']>
  'LazyUiCardTitle': LazyComponent<typeof import("../../components/ui/card-title.vue")['default']>
  'LazyUiCard': LazyComponent<typeof import("../../components/ui/card")['default']>
  'LazyUiCarousel': LazyComponent<typeof import("../../components/ui/carousel")['default']>
  'LazyUiChartArea': LazyComponent<typeof import("../../components/ui/chart-area.vue")['default']>
  'LazyUiChartBar': LazyComponent<typeof import("../../components/ui/chart-bar.vue")['default']>
  'LazyUiChartLine': LazyComponent<typeof import("../../components/ui/chart-line.vue")['default']>
  'LazyUiChart': LazyComponent<typeof import("../../components/ui/chart")['default']>
  'LazyUiCheckbox': LazyComponent<typeof import("../../components/ui/checkbox")['default']>
  'LazyUiCollapsible': LazyComponent<typeof import("../../components/ui/collapsible")['default']>
  'LazyUiCommand': LazyComponent<typeof import("../../components/ui/command")['default']>
  'LazyUiContextMenu': LazyComponent<typeof import("../../components/ui/context-menu")['default']>
  'LazyUiDialogDescription': LazyComponent<typeof import("../../components/ui/dialog-description.vue")['default']>
  'LazyUiDialogFooter': LazyComponent<typeof import("../../components/ui/dialog-footer.vue")['default']>
  'LazyUiDialogHeader': LazyComponent<typeof import("../../components/ui/dialog-header.vue")['default']>
  'LazyUiDialogTitle': LazyComponent<typeof import("../../components/ui/dialog-title.vue")['default']>
  'LazyUiDialog': LazyComponent<typeof import("../../components/ui/dialog")['default']>
  'LazyUiDrawer': LazyComponent<typeof import("../../components/ui/drawer")['default']>
  'LazyUiDropdownMenuItem': LazyComponent<typeof import("../../components/ui/dropdown-menu-item.vue")['default']>
  'LazyUiDropdownMenuLabel': LazyComponent<typeof import("../../components/ui/dropdown-menu-label.vue")['default']>
  'LazyUiDropdownMenuSeparator': LazyComponent<typeof import("../../components/ui/dropdown-menu-separator.vue")['default']>
  'LazyUiDropdownMenu': LazyComponent<typeof import("../../components/ui/dropdown-menu")['default']>
  'LazyUiFab': LazyComponent<typeof import("../../components/ui/fab.vue")['default']>
  'LazyUiForm': LazyComponent<typeof import("../../components/ui/form")['default']>
  'LazyUiHoverCard': LazyComponent<typeof import("../../components/ui/hover-card")['default']>
  'LazyUiInputOtp': LazyComponent<typeof import("../../components/ui/input-otp")['default']>
  'LazyUiInput': LazyComponent<typeof import("../../components/ui/input")['default']>
  'LazyUiLabel': LazyComponent<typeof import("../../components/ui/label")['default']>
  'LazyUiMenubar': LazyComponent<typeof import("../../components/ui/menubar")['default']>
  'LazyUiNavigationMenu': LazyComponent<typeof import("../../components/ui/navigation-menu")['default']>
  'LazyUiPagination': LazyComponent<typeof import("../../components/ui/pagination")['default']>
  'LazyUiPopover': LazyComponent<typeof import("../../components/ui/popover")['default']>
  'LazyUiProgress': LazyComponent<typeof import("../../components/ui/progress")['default']>
  'LazyUiRadioGroupItem': LazyComponent<typeof import("../../components/ui/radio-group-item.vue")['default']>
  'LazyUiRadioGroup': LazyComponent<typeof import("../../components/ui/radio-group")['default']>
  'LazyUiResizable': LazyComponent<typeof import("../../components/ui/resizable")['default']>
  'LazyUiScrollArea': LazyComponent<typeof import("../../components/ui/scroll-area")['default']>
  'LazyUiSelectItem': LazyComponent<typeof import("../../components/ui/select-item.vue")['default']>
  'LazyUiSelect': LazyComponent<typeof import("../../components/ui/select")['default']>
  'LazyUiSeparator': LazyComponent<typeof import("../../components/ui/separator")['default']>
  'LazyUiSheet': LazyComponent<typeof import("../../components/ui/sheet")['default']>
  'LazyUiSidebar': LazyComponent<typeof import("../../components/ui/sidebar")['default']>
  'LazyUiSkeleton': LazyComponent<typeof import("../../components/ui/skeleton")['default']>
  'LazyUiSlider': LazyComponent<typeof import("../../components/ui/slider")['default']>
  'LazyUiSonner': LazyComponent<typeof import("../../components/ui/sonner")['default']>
  'LazyUiSwitch': LazyComponent<typeof import("../../components/ui/switch")['default']>
  'LazyUiTable': LazyComponent<typeof import("../../components/ui/table")['default']>
  'LazyUiTabsContent': LazyComponent<typeof import("../../components/ui/tabs-content.vue")['default']>
  'LazyUiTabsList': LazyComponent<typeof import("../../components/ui/tabs-list.vue")['default']>
  'LazyUiTabsTrigger': LazyComponent<typeof import("../../components/ui/tabs-trigger.vue")['default']>
  'LazyUiTabs': LazyComponent<typeof import("../../components/ui/tabs")['default']>
  'LazyUiTextarea': LazyComponent<typeof import("../../components/ui/textarea")['default']>
  'LazyUiToast': LazyComponent<typeof import("../../components/ui/toast.vue")['default']>
  'LazyUiToggleGroupItem': LazyComponent<typeof import("../../components/ui/toggle-group-item.vue")['default']>
  'LazyUiToggleGroup': LazyComponent<typeof import("../../components/ui/toggle-group")['default']>
  'LazyUiToggle': LazyComponent<typeof import("../../components/ui/toggle")['default']>
  'LazyUiTooltip': LazyComponent<typeof import("../../components/ui/tooltip")['default']>
  'LazyUiUseMobile': LazyComponent<typeof import("../../components/ui/use-mobile")['default']>
  'LazyUiUtils': LazyComponent<typeof import("../../components/ui/utils")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
