# Generated by Django 5.2.8 on 2025-11-18 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(editable=False, help_text='Human-readable ticket number (e.g., TKT-2024-00123)', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical Issue'), ('billing', 'Billing Question'), ('access', 'Account Access'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('other', 'Other')], default='other', help_text='Type of issue or request', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low (72h SLA)'), ('medium', 'Medium (24h SLA)'), ('high', 'High (8h SLA)'), ('critical', 'Critical (2h SLA)')], default='medium', help_text='Urgency level (affects SLA)', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('pending', 'Pending Customer Response'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], db_index=True, default='new', help_text='Current ticket status', max_length=20)),
                ('subject', models.CharField(help_text='Brief summary of the issue', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('sla_due_date', models.DateTimeField(help_text='When ticket should be resolved (based on priority)')),
                ('sla_breached', models.BooleanField(default=False, help_text='Whether SLA deadline was missed')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When ticket was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Support agent assigned to this ticket', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Customer who created this ticket', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Message content')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note (not visible to customer)')),
                ('is_system', models.BooleanField(default=False, help_text='Auto-generated system message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(help_text='Message author (customer or agent)', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Parent support ticket', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'db_table': 'ticket_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRecoveryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('password_reset', 'Password Reset'), ('2fa_reset', '2FA Reset'), ('account_unlock', 'Account Unlock'), ('email_change', 'Email Change')], help_text='Type of access recovery', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Identity Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Current request status', max_length=20)),
                ('verification_method', models.CharField(blank=True, choices=[('email', 'Email Verification'), ('sms', 'SMS Verification'), ('id_document', 'ID Document'), ('support_call', 'Support Call'), ('billing_info', 'Billing Information')], default='', help_text='How user identity was verified', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes for review')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When request was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed the request', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_recovery_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting access recovery', on_delete=django.db.models.deletion.CASCADE, related_name='access_recovery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Recovery Request',
                'verbose_name_plural': 'Access Recovery Requests',
                'db_table': 'access_recovery_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='recovery_time_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['-created_at', 'status'], name='ticket_time_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority', 'status'], name='ticket_pri_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['sla_due_date'], name='ticket_sla_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='msg_ticket_time_idx'),
        ),
    ]
