# Generated by Django 5.2.8 on 2025-11-18 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('system_id', models.CharField(max_length=255, unique=True)),
                ('system_type', models.CharField(choices=[('hydraulic', 'Hydraulic System'), ('pneumatic', 'Pneumatic System'), ('electrical', 'Electrical System'), ('other', 'Other')], default='hydraulic', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('adjacency_matrix', models.JSONField()),
                ('components', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
                'managed': False,
            },
        ),
    ]
