# Generated by Django 5.2.8 on 2025-11-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='docs_docume_slug_53ab62_idx',
            old_name='docs_docume_slug_7f8c3d_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='docs_docume_categor_9ccf00_idx',
            old_name='docs_docume_categor_8e5a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='docs_docume_is_publ_8e7076_idx',
            old_name='docs_docume_is_publ_9d4f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='docs_docume_is_feat_dbfdd0_idx',
            old_name='docs_docume_is_feat_2a6b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='documentcategory',
            new_name='docs_docume_slug_2f9259_idx',
            old_name='docs_docume_slug_4e4a15_idx',
        ),
        migrations.RenameIndex(
            model_name='documentcategory',
            new_name='docs_docume_order_749453_idx',
            old_name='docs_docume_order_5b2c6a_idx',
        ),
        migrations.RenameIndex(
            model_name='userprogress',
            new_name='docs_userpr_user_id_868c35_idx',
            old_name='docs_userpr_user_id_3c7e4d_idx',
        ),
        migrations.RenameIndex(
            model_name='userprogress',
            new_name='docs_userpr_last_vi_b975eb_idx',
            old_name='docs_userpr_last_vi_5d8f6e_idx',
        ),
    ]
