// Mock data service for demo mode
export const useDemoData = () => {
  const demoEquipment = [
    {
      id: 'demo-001',
      name: 'Excavator CAT 320D',
      type: 'excavator_tracked',
      manufacturer: 'Caterpillar',
      model: '320D',
      status: 'active',
      health: 87,
      sensors: 12,
      alerts: 2,
      uptime: 98.5,
      lastMaintenance: '2025-10-15',
    },
    {
      id: 'demo-002',
      name: 'Hydraulic Press HPM-500',
      type: 'press',
      manufacturer: 'Schuler',
      model: 'HPM-500',
      status: 'active',
      health: 92,
      sensors: 8,
      alerts: 0,
      uptime: 99.2,
      lastMaintenance: '2025-11-01',
    },
    {
      id: 'demo-003',
      name: 'Mobile Crane LTM 1300',
      type: 'crane_mobile',
      manufacturer: 'Liebherr',
      model: 'LTM 1300-6.2',
      status: 'maintenance',
      health: 75,
      sensors: 15,
      alerts: 5,
      uptime: 94.8,
      lastMaintenance: '2025-09-20',
    },
    {
      id: 'demo-004',
      name: 'Loader Volvo L350F',
      type: 'loader_wheeled',
      manufacturer: 'Volvo',
      model: 'L350F',
      status: 'active',
      health: 95,
      sensors: 10,
      alerts: 1,
      uptime: 99.5,
      lastMaintenance: '2025-11-05',
    },
  ]

  const demoAlerts = [
    {
      id: 1,
      equipment: 'demo-001',
      equipmentName: 'Excavator CAT 320D',
      severity: 'warning',
      message: 'Pressure slightly elevated in main pump',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      status: 'active',
    },
    {
      id: 2,
      equipment: 'demo-001',
      equipmentName: 'Excavator CAT 320D',
      severity: 'info',
      message: 'Scheduled maintenance due in 5 days',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      status: 'active',
    },
    {
      id: 3,
      equipment: 'demo-003',
      equipmentName: 'Mobile Crane LTM 1300',
      severity: 'critical',
      message: 'Temperature threshold exceeded - immediate attention required',
      timestamp: new Date(Date.now() - 1800000).toISOString(),
      status: 'active',
    },
    {
      id: 4,
      equipment: 'demo-003',
      equipmentName: 'Mobile Crane LTM 1300',
      severity: 'error',
      message: 'Hydraulic fluid level low',
      timestamp: new Date(Date.now() - 5400000).toISOString(),
      status: 'active',
    },
    {
      id: 5,
      equipment: 'demo-004',
      equipmentName: 'Loader Volvo L350F',
      severity: 'info',
      message: 'System performance optimal',
      timestamp: new Date(Date.now() - 10800000).toISOString(),
      status: 'resolved',
    },
  ]

  const demoDiagnostics = [
    {
      id: 'diag-001',
      equipment: 'demo-001',
      equipmentName: 'Excavator CAT 320D',
      status: 'completed',
      healthScore: 87,
      startedAt: new Date(Date.now() - 86400000).toISOString(),
      completedAt: new Date(Date.now() - 85000000).toISOString(),
      duration: '23m 20s',
      issues: 2,
      priority: 'medium',
    },
    {
      id: 'diag-002',
      equipment: 'demo-002',
      equipmentName: 'Hydraulic Press HPM-500',
      status: 'completed',
      healthScore: 92,
      startedAt: new Date(Date.now() - 172800000).toISOString(),
      completedAt: new Date(Date.now() - 171000000).toISOString(),
      duration: '18m 45s',
      issues: 0,
      priority: 'low',
    },
    {
      id: 'diag-003',
      equipment: 'demo-003',
      equipmentName: 'Mobile Crane LTM 1300',
      status: 'processing',
      healthScore: 75,
      startedAt: new Date(Date.now() - 300000).toISOString(),
      completedAt: null,
      duration: 'In progress',
      issues: 5,
      priority: 'high',
    },
    {
      id: 'diag-004',
      equipment: 'demo-004',
      equipmentName: 'Loader Volvo L350F',
      status: 'completed',
      healthScore: 95,
      startedAt: new Date(Date.now() - 259200000).toISOString(),
      completedAt: new Date(Date.now() - 258000000).toISOString(),
      duration: '15m 32s',
      issues: 1,
      priority: 'low',
    },
  ]

  const demoSystems = [
    {
      id: 'sys-001',
      name: 'Production Line A',
      type: 'industrial',
      status: 'active',
      equipment: ['demo-001', 'demo-002'],
      health: 89,
      location: 'Warehouse North',
    },
    {
      id: 'sys-002',
      name: 'Mobile Fleet',
      type: 'mobile',
      status: 'maintenance',
      equipment: ['demo-003', 'demo-004'],
      health: 85,
      location: 'Field Operations',
    },
  ]

  return {
    equipment: demoEquipment,
    alerts: demoAlerts,
    diagnostics: demoDiagnostics,
    systems: demoSystems,
  }
}
