# Generated by Django 5.1.14 on 2025-11-06 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RagSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "model_name",
                    models.CharField(default="openai/gpt-3.5-turbo", max_length=100),
                ),
                ("index_type", models.CharField(default="faiss", max_length=50)),
                (
                    "index_config",
                    models.JSONField(
                        default=dict, verbose_name="Настройки индексатора"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RAG-система",
                "verbose_name_plural": "RAG-системы",
                "indexes": [
                    models.Index(fields=["name"], name="rag_assista_name_e20cb8_idx"),
                    models.Index(
                        fields=["created_at"], name="rag_assista_created_d3a450_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("txt", "PlainText"),
                            ("pdf", "PDF"),
                            ("docx", "Word"),
                            ("md", "Markdown"),
                        ],
                        max_length=10,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Russian"),
                            ("de", "German"),
                        ],
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="Метаданные")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rag_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="rag_assistant.ragsystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.CreateModel(
            name="RagQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("response_text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rag_assistant.document",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="rag_assistant.ragsystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог запроса RAG",
                "verbose_name_plural": "Логи запросов RAG",
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="rag_assista_timesta_e9e99e_idx"
                    ),
                    models.Index(
                        fields=["system", "timestamp"],
                        name="rag_assista_system__a0ba6e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["rag_system", "language"], name="rag_assista_rag_sys_b5140b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="rag_assista_created_1bc1aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["format"], name="rag_assista_format_0e26bd_idx"),
        ),
    ]
