# Generated by Django 5.1.14 on 2025-11-06 23:41

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable sensor node name",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the sensor node",
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("modbus_tcp", "Modbus TCP"),
                            ("modbus_rtu", "Modbus RTU"),
                            ("opcua", "OPC UA"),
                            ("http_json", "HTTP JSON"),
                            ("mqtt", "MQTT"),
                            ("ethernet_ip", "Ethernet/IP"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "host_address",
                    models.GenericIPAddressField(
                        help_text="IP address of the sensor node"
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        help_text="Network port",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "protocol_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Protocol-specific configuration (timeouts, unit ID, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Enable/disable data collection from this node",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=20,
                    ),
                ),
                (
                    "last_data_received",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp of last successful data reception",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", help_text="Last error message"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sensors_node",
                "ordering": ["name"],
                "indexes": [
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["protocol", "is_active"], name="idx_sn_protocol_active"
                    ),
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["status", "last_data_received"],
                        name="idx_sn_status_lastdata",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sensor_name",
                    models.CharField(
                        help_text="Human-readable sensor name", max_length=255
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("pressure", "Pressure"),
                            ("temperature", "Temperature"),
                            ("flow_rate", "Flow Rate"),
                            ("vibration", "Vibration"),
                            ("speed", "Speed/RPM"),
                            ("position", "Position"),
                            ("force", "Force"),
                            ("voltage", "Voltage"),
                            ("current", "Current"),
                            ("power", "Power"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "register_address",
                    models.PositiveIntegerField(
                        help_text="Register address (Modbus) or node ID (OPC UA)"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("float32", "Float 32-bit"),
                            ("float64", "Float 64-bit"),
                            ("int16", "Integer 16-bit"),
                            ("int32", "Integer 32-bit"),
                            ("uint16", "Unsigned Integer 16-bit"),
                            ("uint32", "Unsigned Integer 32-bit"),
                            ("bool", "Boolean"),
                        ],
                        default="float32",
                        max_length=16,
                    ),
                ),
                (
                    "scale_factor",
                    models.FloatField(
                        default=1.0, help_text="Multiply raw value by this factor"
                    ),
                ),
                (
                    "offset",
                    models.FloatField(
                        default=0.0, help_text="Add this offset after scaling"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Physical unit (bar, °C, L/min, etc.)",
                        max_length=32,
                    ),
                ),
                (
                    "sampling_interval_seconds",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Data collection interval in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                (
                    "min_valid_value",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum valid sensor value (for range validation)",
                        null=True,
                    ),
                ),
                (
                    "max_valid_value",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum valid sensor value (for range validation)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_configs",
                        to="sensors.sensornode",
                    ),
                ),
            ],
            options={
                "db_table": "sensors_config",
                "ordering": ["node", "register_address"],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Sensor reading timestamp"
                    ),
                ),
                (
                    "raw_value",
                    models.FloatField(
                        help_text="Raw value from sensor before processing"
                    ),
                ),
                (
                    "processed_value",
                    models.FloatField(
                        help_text="Processed value (scaled and offset applied)"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("uncertain", "Uncertain"),
                            ("bad", "Bad"),
                        ],
                        db_index=True,
                        default="good",
                        max_length=16,
                    ),
                ),
                (
                    "is_quarantined",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if reading failed validation and is quarantined",
                    ),
                ),
                (
                    "quarantine_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reason for quarantine (out of range, communication error, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "collection_latency_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken to collect this reading (milliseconds)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="sensors.sensornode",
                    ),
                ),
                (
                    "sensor_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="sensors.sensorconfig",
                    ),
                ),
            ],
            options={
                "db_table": "sensors_reading",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="sensorconfig",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["node", "sensor_type"], name="idx_sc_node_type"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorconfig",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["is_active", "sampling_interval_seconds"],
                name="idx_sc_active_interval",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sensorconfig",
            unique_together={("node", "register_address")},
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["timestamp", "node"], name="idx_sr_time_node"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["timestamp", "sensor_config"], name="idx_sr_time_config"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["is_quarantined", "timestamp"], name="idx_sr_quarantine_time"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["quality", "timestamp"], name="idx_sr_quality_time"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["timestamp"], name="brin_sr_timestamp"
            ),
        ),
    ]
