# Generated by Django 5.1.14 on 2025-11-06 23:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnostics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_diagnostic_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hydraulicsystem",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hydraulic_systems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_reports",
                to="diagnostics.hydraulicsystem",
            ),
        ),
        migrations.AddField(
            model_name="integrateddiagnosticresult",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrated_results",
                to="diagnostics.hydraulicsystem",
            ),
        ),
        migrations.AddField(
            model_name="mathematicalmodelresult",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="math_model_results",
                to="diagnostics.hydraulicsystem",
            ),
        ),
        migrations.AddField(
            model_name="integrateddiagnosticresult",
            name="math_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="integrated_results",
                to="diagnostics.mathematicalmodelresult",
            ),
        ),
        migrations.AddField(
            model_name="phaseportraitresult",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phase_portrait_results",
                to="diagnostics.hydraulicsystem",
            ),
        ),
        migrations.AddField(
            model_name="integrateddiagnosticresult",
            name="phase_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="integrated_results",
                to="diagnostics.phaseportraitresult",
            ),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_data",
                to="diagnostics.hydraulicsystem",
            ),
        ),
        migrations.AddField(
            model_name="systemcomponent",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="diagnostics.hydraulicsystem",
            ),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensor_data",
                to="diagnostics.systemcomponent",
            ),
        ),
        migrations.AddField(
            model_name="tribodiagnosticresult",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tribo_results",
                to="diagnostics.hydraulicsystem",
            ),
        ),
        migrations.AddField(
            model_name="integrateddiagnosticresult",
            name="tribo_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="integrated_results",
                to="diagnostics.tribodiagnosticresult",
            ),
        ),
        migrations.AddIndex(
            model_name="hydraulicsystem",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["owner", "status"], name="idx_hs_owner_status"
            ),
        ),
        migrations.AddIndex(
            model_name="hydraulicsystem",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["updated_at"], name="brin_hs_updated"
            ),
        ),
        migrations.AddIndex(
            model_name="hydraulicsystem",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True,
                fields=["last_reading_at"],
                name="brin_hs_last_reading",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticreport",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["system", "created_at"], name="idx_dr_system_created"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticreport",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["severity", "created_at"], name="idx_dr_severity_created"
            ),
        ),
        migrations.AddIndex(
            model_name="mathematicalmodelresult",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["system", "timestamp"], name="idx_mmr_system_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="mathematicalmodelresult",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["status", "timestamp"], name="idx_mmr_status_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="mathematicalmodelresult",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["timestamp"], name="brin_mmr_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="phaseportraitresult",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["system", "timestamp"], name="idx_ppr_system_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="phaseportraitresult",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["portrait_type", "timestamp"], name="idx_ppr_type_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="phaseportraitresult",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["timestamp"], name="brin_ppr_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="systemcomponent",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["system", "name"], name="idx_comp_system_name"
            ),
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["system", "timestamp"], name="idx_sd_system_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["sensor_type", "timestamp"], name="idx_sd_type_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["timestamp"], name="brin_sd_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="tribodiagnosticresult",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["system", "analysis_date"], name="idx_tdr_system_date"
            ),
        ),
        migrations.AddIndex(
            model_name="tribodiagnosticresult",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["iso_class", "analysis_date"], name="idx_tdr_iso_date"
            ),
        ),
        migrations.AddIndex(
            model_name="tribodiagnosticresult",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["analysis_date"], name="brin_tdr_date"
            ),
        ),
        migrations.AddIndex(
            model_name="integrateddiagnosticresult",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["system", "timestamp"], name="idx_idr_system_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="integrateddiagnosticresult",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["overall_status", "timestamp"], name="idx_idr_status_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="integrateddiagnosticresult",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["integrated_score", "timestamp"], name="idx_idr_score_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="integrateddiagnosticresult",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["timestamp"], name="brin_idr_ts"
            ),
        ),
    ]
